name: release
on:
  push:
    tags: ["v*"]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: src-tauri
      - run: bun run tauri build
        working-directory: src-tauri
      - uses: softprops/action-gh-release@v2
        with:
          files: src-tauri/target/release/bundle/**/*
          generate_release_notes: true
